### PR TITLE
Integration3 t6 f2 94 restaurant search

### PR DESCRIPTION
**Pull request by MaceeQi**
Updated restaurant dao and controller to include find restaurants by name for restaurant search functionality

### CODE REVIEW

**Comment by bovornc** [comment]
Only works if the search bar input matches a restaurant's name exactly (case sensitive), and crashes the node server if we click the search button without typing anything into the search bar.

**Comment by MaceeQi** [comment]
I'll fix the error handling for empty/blank searches. For searching, it is supposed to only find the restaurant if the name matches exactly but I can try to see if I can find by partial matches

**Review by bovornc — APPROVED** [review]
Works great!

**Review by nala-he — APPROVED** [review]
Works well! Sorry for the delay.

**Pull request merged**
