### PR TITLE
Integration2 t6 f2 74 rest backend dao

### PR DESCRIPTION
**Pull request by nala-he**
Implemented DAO interfaces and DAO for Restaurant, Post, FeaturedItem, and Hour models.

### CODE REVIEW

**Review by bovornc — APPROVED** [review]
I think it looks good!

**Review by MaceeQi — APPROVED** [review]
No comments - looks good!

**Comment by nala-he** [comment]
Merged pull request restaurant DAO (including PostDao, FeaturedItemDao, and HourDao) to integration2. The Post model is the updates component that Yena needs. Let me know if you need me to change its name from Post to Update.

**Review by t1yena — CHANGES_REQUESTED** [review]
Please change the Post model name to update! I think the schema/ model needs to be updated from post to update as well

**Comment by nala-he** [comment]
> Please change the Post model name to update! I think the schema/ model needs to be updated from post to update as well

Renamed Post into Update in schema, model, and dao.

**Comment by t1yena** [comment]
should we remove the updateUpdate and updateFeaturedItem from the daos since we will no longer be doing those features anymore?

**Comment by nala-he** [comment]
> should we remove the updateUpdate and updateFeaturedItem from the daos since we will no longer be doing those features anymore?

Yes! I removed them.

**Pull request merged**
